### PR TITLE
Add button to test server connection

### PR DESCRIPTION
**Pull request by aqt**
Allows the user to test the server connection, which helps in troubleshooting the initial setup.

### CODE REVIEW

**Comment by aqt** [comment]
I have implemented support for API tokens (added in latest version), and opened a PR for that. #3 

Since this PR will need a modification to accommodate tokens it would be good to look at that one first.

**Comment by wshanks** [comment]
Hmm, this PR does not work because it is missing the token input box. That leads to `document.querySelector('#token')` giving `null` and so `document.querySelector('#token').value` gives an exception and `testAPI` can not complete.

Also, I am not  positive but in the debugger it seemed like `document.querySelector()` was giving `null` for `#username` and `#password`. Those boxes were visible,, but I hadn't put anything in them yet. It might be necessary to test them before using `.value` for the case where someone enters a token and never enters a username/password.

**Comment by aqt** [comment]
I was not sure if I should've rebased onto master and force push, haven't had much experience with PRs, so the input field is missing because those changes were not included. I have updated the branch now.

As for `#username` and `#password`, did you enter `document.querySelector(...)` in the console opened by inspecting the extension? Because it will show the generated html document for the background script, not the options page. Otherwise I can't understand how they could be `null` as the script will load after they are created.

**Comment by wshanks** [comment]
I was using the console in the debugger. I'm not sure how the scoping works there. I could print out local variables of the function being debugged but maybe `document.querySelector(...)` still works the way you suggest there. I will just check that this PR works with entering only one of username/password or token in a fresh profile.

**Pull request merged**
